#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugInWeb.MainWeb.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Foundation.cshtml")]
    public class Foundation : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Foundation()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n\r\n<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-a" +
"nswer-neither/ -->\r\n<!--[if lt IE 7]> <html");

WriteLiteral(" class=\"no-js lt-ie9 lt-ie8 lt-ie7\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 7]>    <html");

WriteLiteral(" class=\"no-js lt-ie9 lt-ie8\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 8]>    <html");

WriteLiteral(" class=\"no-js lt-ie9\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral("> <![endif]-->\r\n<!--[if gt IE 8]><!-->\r\n<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    \r\n    ");

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n    \r\n    <title>");

            
            #line 16 "..\..\Views\Shared\_Foundation.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - Welcome to Foundation</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 660), Tuple.Create("\"", 680)
, Tuple.Create(Tuple.Create("", 667), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 667), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    \r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_Foundation.cshtml"
Write(Styles.Render("~/Content/foundation/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Views\Shared\_Foundation.cshtml"
Write(RenderSection("head", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\Shared\_Foundation.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"twelve columns\"");

WriteLiteral(">\r\n            <h2>mvc4 plug-in demo</h2>\r\n            <hr />\r\n        </div>\r\n  " +
"  </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"four columns\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Views\Shared\_Foundation.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Shared\_Foundation.cshtml"
               Html.RenderAction("Menu", "Home"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"eight columns\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Views\Shared\_Foundation.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>        \r\n\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\_Foundation.cshtml"
Write(Scripts.Render("~/bundles/foundation"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Shared\_Foundation.cshtml"
Write(Scripts.Render("~/bundles/knockout"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Shared\_Foundation.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
