#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugInWeb.MainWeb.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Menu.cshtml")]
    public class Menu : System.Web.Mvc.WebViewPage<org.theGecko.Utilities.MefMvc.Menu>
    {
        public Menu()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"tabs vertical hide-on-phones\"");

WriteLiteral(">\r\n    <li>");

            
            #line 4 "..\..\Views\Shared\Menu.cshtml"
   Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 5 "..\..\Views\Shared\Menu.cshtml"
    
            
            #line default
            #line hidden
            
            #line 5 "..\..\Views\Shared\Menu.cshtml"
      Html.RenderPartial("MenuItems", Model.Items);
            
            #line default
            #line hidden
WriteLiteral("\r\n</ul>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
