#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugInWeb.MainWeb.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/MenuItems.cshtml")]
    public class MenuItems : System.Web.Mvc.WebViewPage<ISet<org.theGecko.Utilities.MefMvc.Menu.Item>>
    {
        public MenuItems()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\MenuItems.cshtml"
 foreach (var menuItem in Model)
{
        if (!string.IsNullOrWhiteSpace(menuItem.Action))
        {

            
            #line default
            #line hidden
WriteLiteral("            <li>");

            
            #line 7 "..\..\Views\Shared\MenuItems.cshtml"
           Write(Html.ActionLink(menuItem.Title, menuItem.Action, menuItem.Controller));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 8 "..\..\Views\Shared\MenuItems.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><span>");

            
            #line 11 "..\..\Views\Shared\MenuItems.cshtml"
                                Write(menuItem.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 12 "..\..\Views\Shared\MenuItems.cshtml"
        }
    if (menuItem.Items.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <ul>\r\n");

            
            #line 16 "..\..\Views\Shared\MenuItems.cshtml"
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\MenuItems.cshtml"
              Html.RenderPartial("MenuItems", menuItem.Items);
            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n");

            
            #line 18 "..\..\Views\Shared\MenuItems.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
