// Generated by .NET Reflector from C:\Workbench\DeiCon.Demo.PlugInWeb\packages\RazorGenerator.Mvc.1.5.0.0\lib\net40\RazorGenerator.Mvc.dll

using System.Security;
using System;
using System.IO;
using System.Reflection;

namespace org.theGecko.Utilities.MefMvc
{
    internal static class AssemblyExtensions
    {
        public static DateTime GetLastWriteTimeUtc(this Assembly assembly, DateTime fallback)
        {
            string location = null;
            DateTime lastWriteTimeUtc;
            try
            {
                location = assembly.Location;
            }
            catch (SecurityException)
            {
                Uri uri;
                if ((!string.IsNullOrEmpty(assembly.CodeBase) && Uri.TryCreate(assembly.CodeBase, UriKind.Absolute, out uri)) && uri.IsFile)
                {
                    location = uri.LocalPath;
                }
            }
            if (string.IsNullOrEmpty(location))
            {
                return fallback;
            }
            try
            {
                lastWriteTimeUtc = File.GetLastWriteTimeUtc(location);
                if (lastWriteTimeUtc.Year == 0x641)
                {
                    lastWriteTimeUtc = fallback;
                }
            }
            catch (UnauthorizedAccessException)
            {
                lastWriteTimeUtc = fallback;
            }
            catch (PathTooLongException)
            {
                lastWriteTimeUtc = fallback;
            }
            catch (NotSupportedException)
            {
                lastWriteTimeUtc = fallback;
            }
            return lastWriteTimeUtc;
        }
    }
}
